CREATE TABLE t_pe_category (
  id              VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code       VARCHAR(50)   NOT NULL,
  create_by       VARCHAR(32)   NOT NULL,
  create_time     TIMESTAMP(6)  NOT NULL,
  update_by       VARCHAR(32)   NOT NULL,
  update_time     TIMESTAMP(6)  NOT NULL,
  id_path         VARCHAR(1300) NOT NULL COMMENT 'idPath',
  parent_id       VARCHAR(255) COMMENT '父类ID',
  show_order      FLOAT4        NOT NULL COMMENT '排序',
  category_name   VARCHAR(50)   NOT NULL COMMENT '类别名称',
  category_type   VARCHAR(20)   NOT NULL COMMENT '类别类型(POSITION(岗位), ITEM_BANK(题库), KNOWLEDGE(知识点), ORGANIZE(部门), PAPER(试卷))',
  category_status VARCHAR(20)   NOT NULL COMMENT '状态',
  is_default      BOOL COMMENT '是否默认值',
	INDEX i_pe_category_corpCode(corp_code),
	INDEX i_pe_category_parentId(parent_id)
)COMMENT='类别表';

CREATE TABLE t_pe_file (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  file_name   VARCHAR(100) NOT NULL COMMENT '文件名称',
  file_path   VARCHAR(200) NOT NULL COMMENT '文件路径',
  file_size   INT8         NOT NULL COMMENT '文件大小',
  file_type   VARCHAR(20)  NOT NULL COMMENT '文件类型',
  INDEX i_pes_file_corpCode (corp_code)
)COMMENT='文件表';

CREATE TABLE t_uc_organize (
  id              VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code       VARCHAR(50)   NOT NULL,
  create_by       VARCHAR(32)   NOT NULL,
  create_time     TIMESTAMP(6)  NOT NULL,
  update_by       VARCHAR(32)   NOT NULL,
  update_time     TIMESTAMP(6)  NOT NULL,
  id_path         VARCHAR(1300) NOT NULL COMMENT 'idPath',
  parent_id       VARCHAR(255) COMMENT '父类ID',
  show_order      FLOAT4        NOT NULL COMMENT '排序',
  organize_name   VARCHAR(50)   NOT NULL COMMENT '部门名称',
  organize_status VARCHAR(20)   NOT NULL COMMENT '部门状态',
  is_default      BOOL COMMENT '是否默认值',
  INDEX i_uc_organize_corpCode(corp_code),
  INDEX i_uc_organize_parentId(parent_id)
)COMMENT='部门表';

CREATE TABLE t_uc_position (
  id              VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code       VARCHAR(50)  NOT NULL,
  create_by       VARCHAR(32)  NOT NULL,
  create_time     TIMESTAMP(6) NOT NULL,
  update_by       VARCHAR(32)  NOT NULL,
  update_time     TIMESTAMP(6) NOT NULL,
  position_name   VARCHAR(50)  NOT NULL COMMENT '岗位名称',
  position_status VARCHAR(20)  NOT NULL COMMENT '岗位状态',
  category_id     VARCHAR(32)  NOT NULL COMMENT '岗位类别ID',
  INDEX i_uc_position_categoryId(category_id),
  INDEX i_uc_position_corpcCode(corp_code),
  FOREIGN KEY(category_id) REFERENCES t_pe_category(id)
)COMMENT='岗位表';

CREATE TABLE t_uc_user (
  id             VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code      VARCHAR(50)  NOT NULL,
  create_by      VARCHAR(32)  NOT NULL,
  create_time    TIMESTAMP(6) NOT NULL,
  update_by      VARCHAR(32)  NOT NULL,
  update_time    TIMESTAMP(6) NOT NULL,
  address        VARCHAR(1300) COMMENT '地址',
  email          VARCHAR(100) COMMENT '邮箱',
  email_verify   BOOL DEFAULT FALSE COMMENT '邮箱是否严验证',
  employee_code  VARCHAR(20) COMMENT '工号',
  entry_time     DATE COMMENT '入职时间',
  face_file_id   VARCHAR(32) COMMENT '头像ID',
  face_file_name VARCHAR(200) COMMENT '头像名称',
  id_card        VARCHAR(50) COMMENT '身份证',
  login_name     VARCHAR(50)  NOT NULL COMMENT '用户名',
  mobile         VARCHAR(20) COMMENT '手机号',
  mobile_verify  BOOL DEFAULT FALSE COMMENT '手机号是否验证',
  password       VARCHAR(50)  NOT NULL COMMENT '密码',
  sex_type       VARCHAR(20) COMMENT '性别 MALE(男), FEMALE(女), SECRECY(保密)',
  status         VARCHAR(20)  NOT NULL COMMENT '状态 ENABLE(启用), FORBIDDEN(冻结), DELETED(删除)',
  user_name      VARCHAR(50)  NOT NULL COMMENT '姓名',
  role_type      VARCHAR(20)  NOT NULL COMMENT 'USER(学员), ADMIN(管理员)',
  organize_id    VARCHAR(32)  NOT NULL COMMENT '部门',
  INDEX i_uc_user_corpCode (corp_code),
  INDEX i_uc_user_employeeCode (employee_code),
  INDEX i_uc_user_organizeId (organize_id),
  INDEX i_uc_user_loginName (login_name),
  INDEX i_uc_user_mobile (mobile),
  INDEX i_uc_user_email (email),
  FOREIGN KEY(organize_id) REFERENCES t_uc_organize(id)
)COMMENT='用户表';

CREATE TABLE t_uc_user_position (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  position_id VARCHAR(32)  NOT NULL COMMENT '岗位ID',
  user_id     VARCHAR(32)  NOT NULL COMMENT '用户ID',
  INDEX i_uc_user_position_corpCode (corp_code),
  INDEX i_uc_user_position_positionId (position_id),
  UNIQUE u_uc_user_position_userId_positionId (user_id, position_id),
  FOREIGN KEY(position_id) REFERENCES t_uc_position(id),
  FOREIGN KEY(user_id) REFERENCES t_uc_user(id)
)COMMENT='用户岗位表';

CREATE TABLE t_uc_role (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  assign_type VARCHAR(20) COMMENT '安排方式 PART(部分), ALL(全部)',
  comments    VARCHAR(200) COMMENT '备注',
  role_name   VARCHAR(50)  NOT NULL COMMENT '角色名称',
  is_default  BOOL COMMENT '是否默认',
  INDEX i_uc_role_corpCode (corp_code)
)COMMENT='角色表';

CREATE TABLE t_uc_user_role (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  role_id     VARCHAR(32)  NOT NULL COMMENT '角色ID',
  user_id     VARCHAR(32)  NOT NULL COMMENT '用户ID',
  FOREIGN KEY (role_id) REFERENCES t_uc_role (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  UNIQUE u_uc_user_role_userId_roleId (user_id, role_id),
  INDEX i_uc_user_role_corpCode (corp_code),
  INDEX i_uc_user_role_roleId (role_id)
)COMMENT='用户角色表';

CREATE TABLE t_uc_authority (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)   NOT NULL,
  create_by   VARCHAR(32)   NOT NULL,
  create_time TIMESTAMP(6)  NOT NULL,
  update_by   VARCHAR(32)   NOT NULL,
  update_time TIMESTAMP(6)  NOT NULL,
  id_path     VARCHAR(1300) NOT NULL COMMENT 'idPath',
  parent_id   VARCHAR(255) COMMENT '父类ID',
  show_order  FLOAT4        NOT NULL COMMENT '排序',
  auth_name   VARCHAR(50)   NOT NULL COMMENT '权限名称',
  auth_url    VARCHAR(1300) COMMENT '权限URL',
  auth_code   VARCHAR(50)   NOT NULL COMMENT '权限编号',
  comments    VARCHAR(200) COMMENT '备注',
  INDEX i_uc_authority_corpCode (corp_code),
  INDEX i_uc_authority_parentId (parent_id)
)COMMENT='权限表';

CREATE TABLE t_uc_role_authority (
  id           VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code    VARCHAR(50)  NOT NULL,
  create_by    VARCHAR(32)  NOT NULL,
  create_time  TIMESTAMP(6) NOT NULL,
  update_by    VARCHAR(32)  NOT NULL,
  update_time  TIMESTAMP(6) NOT NULL,
  authority_id VARCHAR(32)  NOT NULL COMMENT '权限ID',
  role_id      VARCHAR(32)  NOT NULL COMMENT '角色ID',
  FOREIGN KEY (authority_id) REFERENCES t_uc_authority (id),
  FOREIGN KEY (role_id) REFERENCES t_uc_role (id),
  UNIQUE u_uc_role_authority_roleId_authrityId (role_id, authority_id),
  INDEX i_uc_role_authority_id (authority_id),
  INDEX i_uc_role_authority_corpCode (corp_code)
) COMMENT='角色权限表';

CREATE TABLE t_ems_item_bank (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  bank_name   VARCHAR(50)  NOT NULL COMMENT '题库名称',
  category_id VARCHAR(32)  NOT NULL COMMENT '类别ID',
  bank_status VARCHAR(20)  NOT NULL COMMENT '题库状态：ENABLE("启用"), DELETE("彻底删除")',
  FOREIGN KEY (category_id) REFERENCES t_pe_category (id),
  INDEX i_ems_item_bank_categoryId (category_id),
  INDEX i_ems_item_bank_corpCode (corp_code)
)COMMENT ='题库表';

CREATE TABLE t_ems_item_bank_auth (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  can_edit    BOOL DEFAULT FALSE COMMENT '是否有编辑权限',
  bank_id     VARCHAR(32)  NOT NULL COMMENT '题库ID',
  user_id     VARCHAR(32)  NOT NULL COMMENT '人员ID',
  FOREIGN KEY (user_id) REFERENCES t_uc_user(id),
  FOREIGN KEY (bank_id) REFERENCES t_ems_item_bank (id),
  UNIQUE u_ems_item_bank_auth_bankId_userId (bank_id, user_id),
  INDEX i_ems_item_bank_auth_userId (user_id),
  INDEX i_ems_item_bank_auth_corpCode (corp_code)
) COMMENT ='题库授权表';

CREATE TABLE t_ems_item_detail (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  item_detail TEXT         NOT NULL COMMENT '试题详情包含题干选项答案',
  INDEX i_emx_item_detail_corpCode (corp_code)
)COMMENT='试题详情表';

CREATE TABLE t_ems_item (
  id                 VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code          VARCHAR(50)  NOT NULL,
  create_by          VARCHAR(32)  NOT NULL,
  create_time        TIMESTAMP(6) NOT NULL,
  update_by          VARCHAR(32)  NOT NULL,
  update_time        TIMESTAMP(6) NOT NULL,
  expire_date        DATE         NOT NULL COMMENT '过期时间',
  security           BOOL         NOT NULL DEFAULT FALSE COMMENT '是否保密',
  item_code          VARCHAR(50)  NOT NULL COMMENT '试题编号',
  language_type      VARCHAR(20)  NOT NULL DEFAULT 'CHINESE' COMMENT '语言：CHINESE(中文), ENGLISH(英文), TRADITIONAL_CHINESE(繁体中文), JAPANESE(日文), KOREAN(韩语)',
  level              VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM' COMMENT '等级SIMPLE(简单), RELATIVELY_SIMPLE(较简单), MEDIUM(中等), MORE_DIFFICULT(较难), DIFFICULT(困难)',
  mark               FLOAT8       NOT NULL COMMENT '分数',
  score_rate         FLOAT8 COMMENT '分率',
  score_setting_type VARCHAR(20) COMMENT '得分设置,用于多选题选中部分选项的得分:ALL(全部分值), PART(部分分值)',
  status             VARCHAR(20)  NOT NULL DEFAULT 'DRAFT' COMMENT '状态:DRAFT(草稿), ENABLE(启用), DISABLE(停用), DELETE(彻底删除)',
  stem_outline       VARCHAR(50)  NOT NULL COMMENT '题干前50字',
  type               VARCHAR(20)  NOT NULL DEFAULT 'SINGLE_SELECTION' COMMENT '类型SINGLE_SELECTION(单选题), MULTI_SELECTION(多选题), INDEFINITE_SELECTION(不定项选择), JUDGMENT(判断题), FILL(填空题), QUESTIONS(问答题)',
  bank_id            VARCHAR(32)  NOT NULL COMMENT '题库ID',
  detail_id          VARCHAR(32)  NOT NULL COMMENT '详情ID',
  FOREIGN KEY (bank_id) REFERENCES t_ems_item_bank (id),
  FOREIGN KEY (detail_id) REFERENCES t_ems_item_detail (id),
  UNIQUE u_ems_item_corpCode_itemCode (corp_code, item_code),
  UNIQUE u_ems_item_detailId (detail_id),
  INDEX i_ems_item_bankId (bank_id),
  INDEX i_ems_item_itemCode (item_code),
  INDEX i_ems_item_createBy (create_by)
)COMMENT = '试题表';

CREATE TABLE t_ems_knowledge (
  id               VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code        VARCHAR(50)  NOT NULL,
  create_by        VARCHAR(32)  NOT NULL,
  create_time      TIMESTAMP(6) NOT NULL,
  update_by        VARCHAR(32)  NOT NULL,
  update_time      TIMESTAMP(6) NOT NULL,
  knowledge_name   VARCHAR(50)  NOT NULL COMMENT '知识点名称',
  category_id      VARCHAR(32)  NOT NULL COMMENT '类别ID',
  knowledge_status VARCHAR(20)  NOT NULL COMMENT '状态：ENABLE("启用"), DELETE("彻底删除")',
  FOREIGN KEY (category_id) REFERENCES t_pe_category (id),
  INDEX i_ems_knowledge_categoryId (category_id)
)COMMENT = '知识点表';

CREATE TABLE t_ems_knowledge_item (
  id           VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code    VARCHAR(50)  NOT NULL,
  create_by    VARCHAR(32)  NOT NULL,
  create_time  TIMESTAMP(6) NOT NULL,
  update_by    VARCHAR(32)  NOT NULL,
  update_time  TIMESTAMP(6) NOT NULL,
  item_id      VARCHAR(32)  NOT NULL COMMENT '题库ID',
  knowledge_id VARCHAR(32)  NOT NULL COMMENT '知识点ID',
  FOREIGN KEY (item_id) REFERENCES t_ems_item (id),
  FOREIGN KEY (knowledge_id) REFERENCES t_ems_knowledge (id),
  UNIQUE u_ems_knowledge_item_knowledgeId_itemId (knowledge_id, item_id),
  INDEX i_ems_knowledge_item_corpCode (corp_code),
  INDEX i_ems_knowledge_item_itemId (item_id)
)COMMENT = '知识题库表';

CREATE TABLE t_ems_paper_template (
  id           VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code    VARCHAR(50)  NOT NULL,
  create_by    VARCHAR(32)  NOT NULL,
  create_time  TIMESTAMP(6) NOT NULL,
  update_by    VARCHAR(32)  NOT NULL,
  update_time  TIMESTAMP(6) NOT NULL,
  security     BOOL DEFAULT FALSE COMMENT '是否绝密',
  paper_code   VARCHAR(50)  NOT NULL COMMENT '试卷编号',
  paper_name   VARCHAR(50)  NOT NULL COMMENT '试卷名称',
  paper_status VARCHAR(20)  NOT NULL COMMENT '状态：ENABLE(启用), DISABLE(停用), DRAFT(草稿)',
  paper_type   VARCHAR(20)  NOT NULL COMMENT '试卷模板类型：FIXED(固定), RANDOM(随机)',
  strategy     VARCHAR(500) COMMENT '随机卷组卷策略JSONB',
  category_id  VARCHAR(32)  NOT NULL COMMENT '类别ID',
  FOREIGN KEY (category_id) REFERENCES t_pe_category (id),
  UNIQUE u_ems_paper_template_corpCode_paperCode (corp_code, paper_code),
  INDEX i_ems_paper_template_paperCode (paper_code),
  INDEX i_ems_paper_template_createBy (create_by),
  INDEX i_ems_paper_template_categoryId (category_id)
)COMMENT = '试卷模板表';

CREATE TABLE t_ems_paper_template_auth (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  template_id VARCHAR(32)  COMMENT '模板ID',
  user_id     VARCHAR(32)  COMMENT '用户ID',
  FOREIGN KEY (template_id) REFERENCES t_ems_paper_template (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  UNIQUE u_ems_paper_template_auth_templateId_userId (template_id, user_id),
  INDEX i_ems_paper_template_auth_corpCode (corp_code),
  INDEX i_ems_paper_template_auth_userId (user_id)
)COMMENT = '试卷模板授权表';

CREATE TABLE t_ems_paper_template_item (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  show_order  FLOAT8       NOT NULL COMMENT '排序',
  item_id     VARCHAR(32)  NOT NULL COMMENT '试题ID',
  template_id VARCHAR(32)  NOT NULL COMMENT '模板ID',
  FOREIGN KEY (item_id) REFERENCES t_ems_item (id),
  FOREIGN KEY (template_id) REFERENCES t_ems_paper_template (id),
  UNIQUE u_ems_paper_template_item_templateId_itemId (template_id, item_id),
  INDEX i_ems_paper_template_item_corpCode (corp_code),
  INDEX i_ems_paper_template_item_itemId (item_id)
)COMMENT = '模板必考题关联表';

CREATE TABLE t_ems_paper_template_strategy (
  id            VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code     VARCHAR(50)  NOT NULL,
  create_by     VARCHAR(32)  NOT NULL,
  create_time   TIMESTAMP(6) NOT NULL,
  update_by     VARCHAR(32)  NOT NULL,
  update_time   TIMESTAMP(6) NOT NULL,
  object_id     VARCHAR(32)  NOT NULL COMMENT '题库ID、知识点ID',
  strategy_type VARCHAR(20)  NOT NULL COMMENT '类型:ITEM_BANK(题库), KNOWLEDGE(知识点)',
  template_id   VARCHAR(32)  NOT NULL COMMENT '模板ID',
  UNIQUE u_ems_paper_template_strategy_templateId_objectId (template_id, object_id),
  INDEX i_ems_paper_template_strategy_corpCode (corp_code),
  INDEX i_ems_paper_template_strategy_createBy (create_by),
  INDEX i_ems_paper_template_strategy_objectId (object_id)
)COMMENT = '组卷策略题库知识点关联表';
-- 考试
CREATE TABLE t_ems_exam (
  id           VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code    VARCHAR(50)  NOT NULL,
  create_by    VARCHAR(32)  NOT NULL,
  create_time  TIMESTAMP(6) NOT NULL,
  update_by    VARCHAR(32)  NOT NULL,
  update_time  TIMESTAMP(6) NOT NULL,
  end_time     TIMESTAMP(6) COMMENT '结束时间',
  exam_code    VARCHAR(50)  NOT NULL COMMENT '考试编号',
  exam_name    VARCHAR(100) NOT NULL COMMENT '考试名称',
  exam_plain   VARCHAR(1300) COMMENT '解释',
  exam_type    VARCHAR(20)  NOT NULL COMMENT '考试类型ONLINE(线上考试), OFFLINE(线下考试), COMPREHENSIVE(综合考试)',
  publish_time TIMESTAMP(6) COMMENT '发布时间',
  start_time   TIMESTAMP(6) COMMENT '开始时间',
  status       VARCHAR(20)  NOT NULL COMMENT '状态DRAFT(草稿)ENABLE(启用)CANCEL(已作废)',
  subject      BOOL         NOT NULL COMMENT '是否科目',
  template_id  VARCHAR(32) COMMENT '模板ID',
  source       VARCHAR(20) COMMENT '来源COPY(复制)EXAM_COPY(启用复制)ADD(新建)',
  mark_up_id   VARCHAR(32) COMMENT '补考来源ID',
  UNIQUE u_ems_exam_corpCode_examCode (corp_code, exam_code),
  FOREIGN KEY (template_id) REFERENCES t_ems_paper_template (id),
  INDEX i_ems_exam_corpCode (corp_code),
  INDEX i_ems_exam_createBy (create_by),
  INDEX i_ems_exam_examCode (exam_code),
  INDEX i_ems_exam_markUpId (mark_up_id),
  INDEX i_ems_exam_templateId (template_id)
)COMMENT '考试表';

CREATE TABLE t_ems_exam_arrange (
  id                   VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code            VARCHAR(50)  NOT NULL,
  create_by            VARCHAR(32)  NOT NULL,
  create_time          TIMESTAMP(6) NOT NULL,
  update_by            VARCHAR(32)  NOT NULL,
  update_time          TIMESTAMP(6) NOT NULL,
  batch_name           VARCHAR(50) COMMENT '批次名称',
  end_time             TIMESTAMP(6) COMMENT '结束时间',
  show_order           FLOAT4       NOT NULL COMMENT '排序',
  start_time           TIMESTAMP(6) COMMENT '开始时间',
  status               VARCHAR(20)  NOT NULL COMMENT '状态ENABLE("启用")CANCEL("已作废")',
  exam_subject_setting VARCHAR(500) COMMENT '科目设置',
  exam_id              VARCHAR(32)  NOT NULL COMMENT '考试ID',
  subject_id           VARCHAR(32) COMMENT '科目ID',
  mark_up_type         VARCHAR(50) COMMENT 'NO_PASS(未通过),MISS_EXAM(缺考)',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (subject_id) REFERENCES t_ems_exam (id),
  INDEX i_ems_exam_arrange_corpCode (corp_code),
  INDEX i_ems_exam_arrange_createBy (create_by),
  INDEX i_ems_exam_arrange_examId (exam_id),
  INDEX i_ems_exam_arrange_subjectId (subject_id)
)COMMENT = '考试安排表';

CREATE TABLE t_ems_exam_auth (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  show_order  FLOAT4 COMMENT '序号',
  exam_id     VARCHAR(32)  NOT NULL COMMENT '考试ID',
  user_id     VARCHAR(32)  NOT NULL COMMENT '用户ID',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  UNIQUE u_ems_exam_auth_examId_userId (exam_id, user_id),
  INDEX i_ems_exam_authc_corpCode (corp_code),
  INDEX i_ems_exam_auth_createBy (create_by),
  INDEX i_ems_exam_auth_examId (exam_id),
  INDEX i_ems_exam_auth_userId (user_id)
) COMMENT = '考试授权表';

CREATE TABLE t_ems_paper (
  id                VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code         VARCHAR(50)  NOT NULL,
  create_by         VARCHAR(32)  NOT NULL,
  create_time       TIMESTAMP(6) NOT NULL,
  update_by         VARCHAR(32)  NOT NULL,
  update_time       TIMESTAMP(6) NOT NULL,
  item_count        INT4 COMMENT '试题数量',
  level             VARCHAR(20)  NOT NULL COMMENT '试题等级',
  mark              FLOAT8 COMMENT '试题总分',
  paper_content     TEXT         NOT NULL COMMENT '试卷试题',
  exam_id           VARCHAR(32) COMMENT '考试',
  paper_template_id VARCHAR(32) COMMENT '试卷模板ID',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (paper_template_id) REFERENCES t_ems_paper_template (id),
  INDEX i_ems_paper_corpCode (corp_code),
  INDEX i_ems_paper_createBy (create_by),
  INDEX i_ems_paper_examId (exam_id),
  INDEX i_ems_paper_paperTemplateId (paper_template_id)
)COMMENT = '试卷表';

CREATE TABLE t_ems_exam_result (
  id             VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code      VARCHAR(50)  NOT NULL,
  create_by      VARCHAR(32)  NOT NULL,
  create_time    TIMESTAMP(6) NOT NULL,
  update_by      VARCHAR(32)  NOT NULL,
  update_time    TIMESTAMP(6) NOT NULL,
  exam_count     INT4         NOT NULL COMMENT '考试次数',
  judge_flag     VARCHAR(20)  NOT NULL COMMENT '最后一次考试的评卷类型AUTO(自动评卷), MANUAL(手动评卷)',
  judge_time     TIMESTAMP(6) COMMENT '最后一次考试的评卷时间',
  total_score    FLOAT8 COMMENT '总分数',
  exam_id        VARCHAR(32)  NOT NULL COMMENT '考试ID',
  user_id        VARCHAR(32)  NOT NULL COMMENT '学员ID',
  score          FLOAT8 COMMENT '最后一次考试的考试真实成绩',
  first_score    FLOAT8 COMMENT '首次成绩',
  need_make_up   BOOL COMMENT '是否需要补考:学员交卷，后台评卷 直接给出，主要针对补考类考试',
  pass           BOOL COMMENT '是否通过',
  publish_time   TIMESTAMP(6) COMMENT '发布时间',
  paper_id       VARCHAR(32) COMMENT '最后一次考试试卷',
  start_time     TIMESTAMP(6) COMMENT '考试开始时间',
  end_time       TIMESTAMP(6) COMMENT '考试结束时间',
  last_result_id VARCHAR(32) COMMENT '最后考试结果ID',
  mark_exam_id   VARCHAR(32) COMMENT '补考考试ID',
  arrange_id     VARCHAR(32) COMMENT '安排ID',
  status         VARCHAR(20)  NOT NULL COMMENT '状态MISS_EXAM("缺考")MARKING("待评卷")RELEASE("已发布")WAIT_RELEASE("待发布成绩")',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  FOREIGN KEY (paper_id) REFERENCES t_ems_paper (id),
  FOREIGN KEY (mark_exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (arrange_id) REFERENCES t_ems_exam_arrange (id),
  UNIQUE u_ems_exam_result_examId_userId (exam_id, user_id),
  INDEX i_ems_exam_result_corpCode (corp_code),
  INDEX i_ems_exam_result_userId (user_id),
  INDEX i_ems_exam_result_last_result_id (last_result_id),
  INDEX i_ems_exam_result_mark_exam_id (mark_exam_id),
  INDEX i_ems_exam_result_arrange_id (arrange_id),
  INDEX i_ems_exam_result_paper_id (paper_id)
)COMMENT = '考试结果表';

CREATE TABLE t_ems_exam_result_detail (
  id           VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code    VARCHAR(50)  NOT NULL,
  create_by    VARCHAR(32)  NOT NULL,
  create_time  TIMESTAMP(6) NOT NULL,
  update_by    VARCHAR(32)  NOT NULL,
  update_time  TIMESTAMP(6) NOT NULL,
  exam_count   INT4         NOT NULL COMMENT '当前次数',
  judge_flag   VARCHAR(20)  NOT NULL COMMENT '评卷标志',
  score        FLOAT8 COMMENT '分数',
  total_score  FLOAT8 COMMENT '总分',
  exam_id      VARCHAR(32)  NOT NULL COMMENT '考试ID',
  paper_id     VARCHAR(32)  NOT NULL COMMENT '试卷ID',
  user_id      VARCHAR(32)  NOT NULL COMMENT '学员ID',
  start_time   TIMESTAMP(6) NOT NULL COMMENT '考试开始时间',
  end_time     TIMESTAMP(6) NOT NULL COMMENT '考试结束时间',
  pass         BOOL COMMENT '是否通过',
  mark_exam_id VARCHAR(32) COMMENT '补考ID',
  result_id    VARCHAR(32) COMMENT '结果ID',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (paper_id) REFERENCES t_ems_paper (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  FOREIGN KEY (mark_exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (result_id) REFERENCES t_ems_exam_result (id),
  INDEX i_ems_exam_result_detail_corpCode (corp_code),
  INDEX i_ems_exam_result_detail_examId (exam_id),
  INDEX i_ems_exam_result_detail_userId (user_id),
  INDEX i_ems_exam_result_detail_markExamId (mark_exam_id),
  INDEX i_ems_exam_result_detail_paperId (paper_id),
  INDEX i_ems_exam_result_detail_resultId (result_id)
)COMMENT = '考试结果详情表';

CREATE TABLE t_ems_exam_setting (
  id              VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code       VARCHAR(50)  NOT NULL,
  create_by       VARCHAR(32)  NOT NULL,
  create_time     TIMESTAMP(6) NOT NULL,
  update_by       VARCHAR(32)  NOT NULL,
  update_time     TIMESTAMP(6) NOT NULL,
  exam_auth_type  VARCHAR(20) COMMENT '考生权限设置',
  exam_setting    VARCHAR(500) COMMENT '考试基本设置',
  judge_setting   VARCHAR(500) COMMENT '评卷策略',
  message_setting VARCHAR(500) COMMENT '消息设置',
  prevent_setting VARCHAR(500) COMMENT '防舞弊设置',
  rank_setting    VARCHAR(500) COMMENT '排行设置',
  score_setting   VARCHAR(500) NOT NULL COMMENT '成绩设置',
  exam_id         VARCHAR(32)  NOT NULL COMMENT '考试ID',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  INDEX i_ems_exam_setting_createBy (create_by),
  INDEX i_ems_exam_setting_examId (exam_id),
  UNIQUE u_ems_exam_setting_corpCode_examId (corp_code, exam_id)
) COMMENT = '考试设置表';

CREATE TABLE t_ems_exam_user (
  id              VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code       VARCHAR(50)  NOT NULL,
  create_by       VARCHAR(32)  NOT NULL,
  create_time     TIMESTAMP(6) NOT NULL,
  update_by       VARCHAR(32)  NOT NULL,
  update_time     TIMESTAMP(6) NOT NULL,
  refer_id        VARCHAR(50)  NOT NULL COMMENT '关联ID',
  refer_type      VARCHAR(20)  NOT NULL COMMENT '关联类型USER(用户), ORGANIZE(组织)',
  show_order      FLOAT8       NOT NULL COMMENT '序号',
  exam_id         VARCHAR(32)  NOT NULL COMMENT '考试ID',
  exam_arrange_id VARCHAR(32) COMMENT '考试安排ID',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (exam_arrange_id) REFERENCES t_ems_exam_arrange (id),
  INDEX i_ems_exam_user_corpCode (corp_code),
  INDEX i_ems_exam_user_examArrangeId (exam_arrange_id),
  INDEX i_ems_exam_user_examId (exam_id)
)COMMENT = '考试安排人员表';

CREATE TABLE t_ems_judge_user (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  rate        FLOAT8 COMMENT '比例',
  refer_id    VARCHAR(32)  NOT NULL COMMENT '关联ID',
  refer_type  VARCHAR(20)  NOT NULL COMMENT 'PAPER(试卷), ITEM(试题)',
  show_order  FLOAT4 COMMENT '排序',
  exam_id     VARCHAR(32)  NOT NULL,
  user_id     VARCHAR(32)  NOT NULL,
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user(id),
  INDEX i_ems_judge_user_examId (exam_id),
  INDEX i_ems_judge_user_referId (refer_id),
  INDEX i_ems_judge_user_userId (user_id),
  INDEX t_ems_judge_user_corpCode (corp_code)
)COMMENT = '评卷关联表';

CREATE TABLE t_ems_judge_user_record (
  id               VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code        VARCHAR(50)  NOT NULL,
  create_by        VARCHAR(32)  NOT NULL,
  create_time      TIMESTAMP(6) NOT NULL,
  update_by        VARCHAR(32)  NOT NULL,
  update_time      TIMESTAMP(6) NOT NULL,
  approval_type    VARCHAR(20)  NOT NULL COMMENT 'MARK(评卷), REVIEW(复评)',
  judge_type       VARCHAR(20)  NOT NULL COMMENT 'PAPER(试卷), ITEM(试题)',
  refer_id         VARCHAR(32)  NOT NULL COMMENT '关联ID',
  score            FLOAT8       NOT NULL COMMENT '分数',
  season           VARCHAR(50) COMMENT '原因',
  mark_detail      TEXT COMMENT '详情JSONB',
  exam_id          VARCHAR(32) COMMENT '考试ID',
  make_user_id     VARCHAR(32) COMMENT '评卷人',
  user_id          VARCHAR(32) COMMENT '学员',
  result_detail_id VARCHAR(32) COMMENT '考试结果对应ID',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (make_user_id) REFERENCES t_uc_user (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  FOREIGN KEY (result_detail_id) REFERENCES t_ems_exam_result_detail (id),
  INDEX i_judge_user_record_examId (exam_id),
  INDEX i_judge_user_record_makeUserId (make_user_id),
  INDEX i_judge_user_record_referId (refer_id),
  INDEX i_judge_user_record_userId (user_id),
  INDEX i_judge_user_record_corpCode (corp_code),
  INDEX i_judge_user_record_resultDetailId (result_detail_id)
)COMMENT = '评卷结果表';

CREATE TABLE t_ems_exam_monitor (
  id               VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code        VARCHAR(50)  NOT NULL,
  create_by        VARCHAR(32)  NOT NULL,
  create_time      TIMESTAMP(6) NOT NULL,
  update_by        VARCHAR(32)  NOT NULL,
  update_time      TIMESTAMP(6) NOT NULL,
  cut_screen_count INT4 COMMENT '切屏次数',
  exam_end_time    TIMESTAMP(6) NOT NULL COMMENT '考试结束时间',
  exam_start_time  TIMESTAMP(6) NOT NULL COMMENT '考试开始时间',
  exam_time        TIMESTAMP(6) COMMENT '进入考试时间',
  force_submit     BOOL COMMENT '是否强制提交',
  illegal_count    INT4 COMMENT '违规次数',
  duration         FLOAT8 COMMENT '答题时长',
  exam_record      TEXT COMMENT '考试记录',
  exit_times       INT4 COMMENT '退出次数',
  answer_status    VARCHAR (20) COMMENT '答题类型NO_ANSWER(未作答), ANSWERING(正在作答), SUBMIT_EXAM(已交卷)',
  submit_time      TIMESTAMP(6) COMMENT '提交时间',
  exam_id          VARCHAR(32) COMMENT '考试ID',
  user_id          VARCHAR(32) COMMENT '学员ID',
  arrange_id       VARCHAR(32) COMMENT '批次ID',
  exam_image       TEXT COMMENT '监控图片ID逗号分隔',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  FOREIGN KEY (arrange_id) REFERENCES t_ems_exam_arrange (id),
  INDEX i_ems_exam_monitor_corpCode (corp_code),
  INDEX i_ems_exam_monitor_examId (exam_id),
  UNIQUE u_ems_exam_monitor_userId_examId (user_id, exam_id)
)COMMENT = '下发监控表';

CREATE TABLE t_ems_exam_illegal_record (
  id              VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code       VARCHAR(50)  NOT NULL,
  create_by       VARCHAR(32)  NOT NULL,
  create_time     TIMESTAMP(6) NOT NULL,
  update_by       VARCHAR(32)  NOT NULL,
  update_time     TIMESTAMP(6) NOT NULL,
  illegal_type    VARCHAR(20)  NOT NULL COMMENT '违纪类型(STATUS:状态异常,IDENTITY:身份异常,OTHER:其他)',
  illegal_content VARCHAR(500) COMMENT '其他内容',
  exam_id         VARCHAR(32)  NOT NULL COMMENT '考试ID',
  user_id         VARCHAR(32)  NOT NULL COMMENT '学员ID',
  process_user_id VARCHAR(32)  NOT NULL COMMENT '处理人',
  monitor_id      VARCHAR(32)  NOT NULL COMMENT '监控ID',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  FOREIGN KEY (process_user_id) REFERENCES t_uc_user (id),
  FOREIGN KEY (monitor_id) REFERENCES t_ems_exam_monitor (id),
  INDEX i_ems_exam_illegal_record_corpCode (corp_code),
  INDEX i_ems_exam_illegal_record_userId (user_id),
  INDEX i_ems_exam_illegal_record_examId (exam_id),
  INDEX i_ems_exam_illegal_record_monitorId (monitor_id),
  INDEX i_ems_exam_illegal_record_processUserId (process_user_id)
)COMMENT = '违规记录表';


CREATE TABLE t_ems_user_exam_record (
  id          VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code   VARCHAR(50)  NOT NULL,
  create_by   VARCHAR(32)  NOT NULL,
  create_time TIMESTAMP(6) NOT NULL,
  update_by   VARCHAR(32)  NOT NULL,
  update_time TIMESTAMP(6) NOT NULL,
  score       FLOAT8 COMMENT '折合分',
  total_score FLOAT8 COMMENT '满分',
  exam_id     VARCHAR(32)  NOT NULL COMMENT '考试ID',
  item_id     VARCHAR(32)  NOT NULL COMMENT '试题ID',
  user_id     VARCHAR(32)  NOT NULL COMMENT '学员ID',
  answer      TEXT COMMENT '学员答案',
  sign        BOOL COMMENT '是否标记',
  paper_id    VARCHAR(32)  NOT NULL COMMENT '试卷ID',
  real_score  FLOAT4 COMMENT '真实分数',
  detail_id   VARCHAR(32)  NOT NULL COMMENT '答卷详情ID',
  FOREIGN KEY (exam_id) REFERENCES t_ems_exam (id),
  FOREIGN KEY (item_id) REFERENCES t_ems_item (id),
  FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
  FOREIGN KEY (paper_id) REFERENCES t_ems_paper (id),
  FOREIGN KEY (detail_id) REFERENCES t_ems_exam_result_detail (id),
  INDEX i_ems_user_exam_record_corpCode (corp_code),
  INDEX i_ems_user_exam_record_examId (exam_id),
  INDEX i_ems_user_exam_record_itemId (item_id),
  INDEX i_ems_user_exam_record_userId (user_id),
  INDEX i_ems_user_exam_record_paperId (paper_id),
  INDEX i_ems_user_exam_record_detailId (detail_id)
)COMMENT = '学员试题答题记录表';

CREATE TABLE t_pe_job (
  id              VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code       VARCHAR(50)  NOT NULL,
  create_by       VARCHAR(32)  NOT NULL,
  create_time     TIMESTAMP(6) NOT NULL,
  update_by       VARCHAR(32)  NOT NULL,
  update_time     TIMESTAMP(6) NOT NULL,
  cron_expression VARCHAR(100) NOT NULL COMMENT '时间表达式',
  cycle           BOOL COMMENT '是否循环',
  execute_status  VARCHAR(20)  NOT NULL COMMENT '执行状态SUCCESS("成功"), FAILED("失败"), DOING("进行中"), NO_START("未开始")',
  function_code   VARCHAR(50)  NOT NULL COMMENT '编号',
  job_name        VARCHAR(100) COMMENT '名称',
  source_id       VARCHAR(32) COMMENT '源ID',
  INDEX i_pe_job_corpCode (corp_code),
  INDEX i_pe_job_courseId (source_id)
)COMMENT = '定时任务';

CREATE TABLE t_pe_job_log (
  id             VARCHAR(32) PRIMARY KEY COMMENT '主键',
  corp_code      VARCHAR(50)   NOT NULL,
  create_by      VARCHAR(32)   NOT NULL,
  create_time    TIMESTAMP(6)  NOT NULL,
  update_by      VARCHAR(32)   NOT NULL,
  update_time    TIMESTAMP(6)  NOT NULL,
  execute_status VARCHAR(20)   NOT NULL COMMENT '执行状态SUCCESS("成功"), FAILED("失败")',
  msg_detail     VARCHAR(1300) NOT NULL COMMENT '详细信息',
  job_id         VARCHAR(32)   NOT NULL COMMENT 'JOBID',
  FOREIGN KEY (job_id) REFERENCES t_pe_job (id),
  INDEX i_pe_job_log_jobId (job_id),
  INDEX i_pe_job_log_corpCode (corp_code)
)COMMENT = '日志表';

CREATE TABLE t_pe_message (
	id VARCHAR (32) PRIMARY KEY COMMENT '主键',
	corp_code VARCHAR (50) NOT NULL,
	create_by VARCHAR (32) NOT NULL,
	create_time TIMESTAMP (6) NOT NULL,
	update_by VARCHAR (32) NOT NULL,
	update_time TIMESTAMP (6) NOT NULL,
	content VARCHAR (1300) NOT NULL COMMENT '内容',
	user_id VARCHAR (32) NOT NULL COMMENT '学员',
	IS_READ BOOL NOT NULL COMMENT '是否已读',
	FOREIGN KEY (user_id) REFERENCES t_uc_user (id),
	INDEX i_pe_message_userId (user_id),
	INDEX i_pe_message_corpCode (corp_code)
) COMMENT = '站内信表';

CREATE TABLE t_pe_corp_info (
  id VARCHAR (32) PRIMARY KEY COMMENT '主键',
  corp_code VARCHAR (50) NOT NULL,
  create_by VARCHAR (32) NOT NULL,
  create_time TIMESTAMP (6) NOT NULL,
  update_by VARCHAR (32) NOT NULL,
  update_time TIMESTAMP (6) NOT NULL,
  address VARCHAR (200) COMMENT '公司地址',
  comments VARCHAR (1300) COMMENT '备注',
  concurrent_num INT8 NOT NULL COMMENT '最大并发数',
  contacts VARCHAR (20) COMMENT '联系人',
  contacts_mobile VARCHAR (20) COMMENT '联系人联系方式',
  corp_name VARCHAR (50) NOT NULL COMMENT '公司名称',
  corp_status VARCHAR (20) NOT NULL COMMENT '状态',
  domain_name VARCHAR (200) NOT NULL COMMENT '域名',
  email VARCHAR (200) COMMENT '邮件',
  end_time TIMESTAMP (6) COMMENT '结束时间',
  industry VARCHAR (200) COMMENT '行业',
  register_num INT8 NOT NULL COMMENT '注册数',
  start_time TIMESTAMP (6) NOT NULL COMMENT '开始时间',
  INDEX i_pe_corp_info_corpCode (corp_code)
) COMMENT = '公司表';