开通试用账号提醒<br/>
申请人信息<br/>
姓名：${CONTACTS!}<br/>
手机：${CONTACTS_MOBILE!}<br/>
邮箱：${CONTACTS_EMAIL!}<br/>
公司：${CORP_NAME!}<br/>
职位：${CONTACTS_POSITION!}<br/>
试用账号信息<br/>
登录地址：${DOMAIN!}<br/>
创建时间：${START_TIME!}